import { StyleSheet } from "react-native";
//import theme from "../theme";

export default StyleSheet.create({
    //...theme,
    sizing_container : {
        flex :1,
        flexDirection:"row"
    },
    sizing_view : {
        width : 90,
        height : 90,
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        paddingRight:5,
        paddingLeft:5,
        borderRadius: 50,
        backgroundColor: '#000',
        //backgroundColor: theme.color.backgroundColor,
    },
    sizing_megaSmall : {
        width : 50,
        height : 50,
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        paddingRight:5,
        paddingLeft:5,
        borderRadius: 50,
        backgroundColor: '#000',
    },
    sizing_midSmall : {
        width : 70,
        height : 70,
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        paddingRight:5,
        paddingLeft:5,
        borderRadius: 50,
        backgroundColor: '#000',
    },
    sizing_small : {
        width : 80,
        height : 80,
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        paddingRight:5,
        paddingLeft:5,
        borderRadius: 50,
        backgroundColor: '#000',
    },
    sizing_midium : {
        width : 90,
        height : 90,
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        paddingRight:5,
        paddingLeft:5,
        borderRadius: 50,
        backgroundColor: '#000',
    },
    sizing_big : {
        width : 120,
        height : 120,
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        paddingRight:5,
        paddingLeft:5,
        borderRadius: 60,
        backgroundColor: '#000',
    },
});