import { StyleSheet } from "react-native";
import theme from "../tstheme";

export default StyleSheet.create({
    buttons_container : {
        flexDirection:"row",
    },
    buttons_small : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        paddingRight:10,
        paddingLeft:10,
        paddingTop: 5,
        paddingBottom: 5,
        borderRadius: 5,
        backgroundColor:theme.baseColor.backgroundColor,
    },
    buttons_default : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        paddingRight:13,
        paddingLeft:13,
        paddingTop: 10,
        paddingBottom: 10,
        borderRadius: 7,
        backgroundColor:theme.baseColor.backgroundColor,
    },
    buttons_big : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        paddingRight:20,
        paddingLeft:20,
        paddingTop: 15,
        paddingBottom: 15,
        borderRadius: 8,
        backgroundColor:theme.baseColor.backgroundColor,
    },
    buttons_text : {
        fontSize:theme.defaultFont.fontSize,
        color:theme.color.backgroundColor,
    },
    buttons_primary : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.primary.backgroundColor,
        backgroundColor:theme.primary.backgroundColor,
    },
    buttons_secondary : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.secondary.backgroundColor,
        backgroundColor:theme.secondary.backgroundColor,
    },
    buttons_success : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.success.backgroundColor,
        backgroundColor:theme.success.backgroundColor,
    },
    buttons_danger : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.danger.backgroundColor,
        backgroundColor:theme.danger.backgroundColor,
    },
    buttons_warning : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.warning.backgroundColor,
        backgroundColor:theme.warning.backgroundColor,
    },
    buttons_info : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.info.backgroundColor,
        backgroundColor:theme.info.backgroundColor,
    },
    buttons_light : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.light.backgroundColor,
        backgroundColor:theme.light.backgroundColor,
    },
    buttons_dark : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.dark.backgroundColor,
        backgroundColor:theme.dark.backgroundColor,
    },
    buttons_link : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 10,
        backgroundColor:theme.color.backgroundColor,
    },
    buttons_primaryBorder : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.primary.backgroundColor,
    },
    buttons_secondaryBorder : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.secondary.backgroundColor,
    },
    buttons_successBorder : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.success.backgroundColor,
    },
    buttons_dangerBorder : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.danger.backgroundColor,
    },
    buttons_warningBorder : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.warning.backgroundColor,
    },
    buttons_infoBorder : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.info.backgroundColor,
    },
    buttons_lightBorder : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.light.backgroundColor,
    },
    buttons_darkBorder : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        padding : 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor:theme.dark.backgroundColor,
    },
    buttons_fullAndBordertext : { 
        fontSize: theme.defaultFont.fontSize,
        color:theme.color.backgroundColor,
    },
    buttons_primaryTextColor : {
        fontSize: theme.defaultFont.fontSize,
        color:theme.primary.backgroundColor,
    },
    buttons_secondaryTextColor : {
        fontSize: theme.defaultFont.fontSize,
        color:theme.secondary.backgroundColor,
    },
    buttons_successTextColor : {
        fontSize: theme.defaultFont.fontSize,
        color:theme.success.backgroundColor,
    },
    buttons_dangerTextColor : {
        fontSize: theme.defaultFont.fontSize,
        color:theme.danger.backgroundColor,
    },
    buttons_warningTextColor : {
        fontSize: theme.defaultFont.fontSize,
        color:theme.warning.backgroundColor,
    },
    buttons_infoTextColor : {
        fontSize: theme.defaultFont.fontSize,
        color:theme.info.backgroundColor,
    },
    buttons_lightTextColor : {
        fontSize: theme.defaultFont.fontSize,
        color:theme.light.backgroundColor,
    },
    buttons_darkTextColor : {
        fontSize: theme.defaultFont.fontSize,
        color:theme.dark.backgroundColor,
    },
    buttons_checkIconButtonDefaultText : {
        fontSize : theme.defaultFont.fontSize,
        color : theme.color.color
    },
    buttons_row : {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    buttons_checkIconDefault : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        paddingRight:15,
        paddingLeft:15,
        paddingTop :10,
        paddingBottom :10,
        borderRadius: 7,
        borderWidth: 1,
        borderColor:theme.light.backgroundColor,
    },
    buttons_checkIconPrimaryBorder : {
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
        paddingRight:15,
        paddingLeft:15,
        paddingTop :10,
        paddingBottom :10,
        borderRadius: 7,
        borderWidth: 1,
        borderColor:theme.primary.backgroundColor,
    },
});